name: calm_cast
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  uuid: ^4.0.0
  http: any
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.5
  connectivity_plus: ^5.0.1
  dio_cache_interceptor: ^3.4.4
  syncfusion_flutter_calendar: ^23.1.40
  flutter_cool_card_swiper: ^0.0.4
  easy_date_timeline: ^0.1.1
  calendar_timeline: ^1.1.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  logger: ^2.0.2+1
  flutter_localization: ^0.1.14

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

